### ISSUE TITLE
NCR parks are missing from nps.nps-places-reference (PT3 feedback)

### ISSUE THREAD

**Issue by jakecoolidge** [nationalparkservice/places-data#279]
Cynthia noticed that some Places trails are overlapping OSM trails in Washington, near where 17th St SW meets Independence Ave SW. In this area, OSM data are not getting clipped out, since the park unit in the area, The National World War II Memorial, appears to be missing from nps.nps-places-reference.

I quickly threw some data into MB and made the following views of the data in downtown Washington. The first shows nps.nps-places-reference boundaries in the area with a green fill and a black boundary. The second overlays, in transparent red, park boundaries from nps.nps-places-boundaries.

![washington-places-ref](https://cloud.githubusercontent.com/assets/11392872/11482941/dc85718c-9762-11e5-8b8b-07a4b7f4e718.png)

![washington-places-ref-places-boundaries](https://cloud.githubusercontent.com/assets/11392872/11482949/e3964690-9762-11e5-836d-2e44d15c22c0.png)

**Comment by chadlawlis** [comment]
Hopefully the new boundaries from Cynthia will address this: https://github.com/nationalparkservice/places-data/issues/347.

**Comment by mtaylorlong** [comment]
With the latest boundaries update, all the boundaries are rendering and should be knocking out trails. This should fix this issue.

**Comment by chadlawlis** [comment]
The the NCR boundary geometries have not been updated. So, the WWII Memorial (unit code NWWM or WWII as seen on NPS.gov) is still not there. This is actually lumped into NCR's boundary for NAMA, so we might want to add NWWM as a "label only site" once the new boundary/labeling table schema goes live.

I'd like to reopen this and only close once NCR boundaries have been updated and the NWWM area has been covered by a park boundary (NAMA).

**Comment by mtaylorlong** [comment]
No problem. Moving this to milestone 3.0.2.

**Comment by chadlawlis** [comment]
NCR boundaries have been updated, and WWII (alternate unit code NWWM) has been added with a boundary from Lands, which will knock out OSM data in the area of concern.
